const defaultData = [
  {
    id: '123',
    pictures: [],
    field: 'name',
    visible: true,
    label: '名字',
    width: 'md',
    searchable: true,
    editable: true,
    inputType: 'input',
    sort: 0,
  },
  {
    id: '124',
    pictures: [],
    field: 'sex',
    visible: true,
    label: '性别',
    width: 'sm',
    searchable: true,
    editable: true,
    inputType: 'select',
    sort: 1,
  },
  {
    id: '125',
    pictures: [],
    field: 'birthday',
    visible: true,
    label: '生日',
    width: 'md',
    searchable: false,
    editable: true,
    inputType: 'date',
    sort: 2,
  },
  {
    id: '126',
    pictures: [],
    field: 'address',
    visible: true,
    label: '地址',
    width: 'xl',
    searchable: false,
    editable: true,
    inputType: 'input',
    sort: 3,
  },
];

export default defaultData;
